services:

  client:
    container_name: bugdothouse_client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app/client

  db:
    container_name: bugdothouse_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=bugdothouse
      - POSTGRES_PASSWORD=bugdothouse
      - POSTGRES_DB=bugdothouse


  wsgi:
    container_name: bugdothouse_wsgi
    build:
      context: ./server
      dockerfile: Dockerfile
    command: uwsgi --socket=:9000 --module=bugdothouse_server.wsgi:application --py-autoreload=1
    restart: always
    volumes:
      - ./server:/opt/bugdothouse
    env_file:
      - ./server/.env
    depends_on:
      - db


  asgi:
    container_name: bugdothouse_asgi
    build:
      context: ./server
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 8000 bugdothouse_server.asgi:application
    restart: always
    volumes:
      - ./server:/opt/bugdothouse
    env_file:
      - ./server/.env
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: bugdothouse_nginx
    volumes:
      - .docker/nginx:/etc/nginx/conf.d
      - ./server/static:/var/www/static
    ports:
      - "80:80"
    depends_on:
      - asgi
      - wsgi

  fairy-stockfish:
    container_name: bugdothouse_fairy-stockfish
    build: .docker/fairy-stockfish

volumes:
  postgres_data: