services:

  client:
    container_name: bugdothouse_client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client

  db:
    container_name: bugdothouse_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bugdothouse
      - POSTGRES_PASSWORD=bugdothouse
      - POSTGRES_DB=bugdothouse


  wsgi:
    container_name: bugdothouse_wsgi
    build:
      context: ./server
      dockerfile: Dockerfile
    command: uwsgi --socket=:9000 --module=bugdothouse_server.wsgi:application --py-autoreload=1
    volumes:
      - ./server:/opt/myproject
    env_file:
      - ./server/.env
    depends_on:
      - db
    tty: true


  asgi:
    container_name: bugdothouse_asgi
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python3 manage.py runserver
    volumes:
      - ./server:/opt/myproject
    env_file:
      - ./server/.env
    depends_on:
      - db
    tty: true

  nginx:
    image: nginx
    container_name: bugdothouse_nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"

volumes:
  postgres_data: